"""Experimental MAS typed state facade."""

from src.agent.mas_types import (
    AgentTask,
    Artifact,
    CriticReport,
    CriticRuntimeAcceptance,
    EvidenceRecord,
    FinalCarryForwardProjection,
    FinalReport,
    MultiAgentState,
    ReportScope,
    TaskStatus,
    WorkerArtifactBoundary,
    attach_task_artifact_trace,
    build_agent_task,
    build_artifact,
    build_critic_report,
    build_evidence_record,
    build_final_report_record,
    critic_report_runtime_acceptance_state,
    project_final_report_carry_forward,
    project_mas_task_artifact_trace,
    project_worker_artifact_boundary,
)

__all__ = [
    "AgentTask",
    "Artifact",
    "CriticReport",
    "CriticRuntimeAcceptance",
    "EvidenceRecord",
    "FinalCarryForwardProjection",
    "FinalReport",
    "MultiAgentState",
    "ReportScope",
    "TaskStatus",
    "WorkerArtifactBoundary",
    "attach_task_artifact_trace",
    "build_agent_task",
    "build_artifact",
    "build_critic_report",
    "build_evidence_record",
    "build_final_report_record",
    "critic_report_runtime_acceptance_state",
    "project_final_report_carry_forward",
    "project_mas_task_artifact_trace",
    "project_worker_artifact_boundary",
]
